
import { Area } from './types';

export const CHECKLIST_TEMPLATES: Record<Area, string[]> = {
  [Area.DFP2]: [
    'Pressão do ar de sopragem (Bar)',
    'Nível de óleo da unidade hidráulica',
    'Integridade das lonas do filtro',
    'Vazamentos em mangueiras de polpa',
    'Alinhamento dos sensores de proximidade',
    'Funcionamento do sistema de lavagem'
  ],
  [Area.BOMBEAMENTO]: [
    'SECTION:VACUUM PUMPS – PLANTA C',
    '06C-VP-101',
    '06C-VP-201',
    '06C-VP-301',
    '06C-VP-401',
    '06C-VP-501',
    'SECTION:VACUUM PUMPS – PLANTA D',
    '06D-VP-101',
    '06D-VP-201',
    '06D-VP-301',
    '06D-VP-401',
    '06D-VP-501',
    'SECTION:FILTRATE PUMPS – PLANTA C',
    '06C-PP-104',
    '06C-PP-105',
    '06C-PP-204',
    '06C-PP-205',
    '06C-PP-304',
    '06C-PP-305',
    'SECTION:FILTRATE PUMPS – PLANTA D',
    '06D-PP-104',
    '06D-PP-105',
    '06D-PP-204',
    '06D-PP-205',
    '06D-PP-304',
    '06D-PP-305',
    'SECTION:CLEAN WATER – PLANTA C',
    '9C-PP-107',
    '9C-PP-109',
    '9C-PP-110',
    '9C-PP-117',
    'SECTION:CLEAN WATER – PLANTA D',
    '9D-PP-107',
    '9D-PP-109',
    '9D-PP-110',
    '9D-PP-117',
    'SECTION:COLUMN WASH',
    '6C-PP-103',
    '6D-PP-103',
    'SECTION:FLOTATION FEED',
    '5C-PP-101',
    '5D-PP-101',
    'SECTION:CLOTH WASH',
    '6C-PP-201',
    '6D-PP-201',
    'SECTION:CONCENTRADO – PLANTA C',
    '6C-PP-102',
    '6C-PP-202',
    '6C-PP-302',
    'SECTION:CONCENTRADO – PLANTA D',
    '6D-PP-201',
    '6D-PP-202',
    '6D-PP-203',
    'SECTION:BOMBAS DO 104',
    '6C-PP-107',
    '6C-PP-207',
    '6C-PP-307',
    'SECTION:SPILLAGE PUMPS – PLANTA C',
    '6C-PP-210',
    '6C-PP-211',
    '6C-PP-212',
    '7C-PP-114',
    '6C-PP-106',
    'SECTION:SPILLAGE PUMPS – PLANTA D',
    '6D-PP-210',
    '6D-PP-211',
    '6D-PP-212',
    '7D-PP-109',
    '7D-PP-108',
    '9D-PP-106'
  ],
  [Area.ESPESADORES]: [
    'Torque do acionamento (%)',
    'Altura dos braços (Rake)',
    'Fluxo de floculante (m3/h)',
    'Densidade do Underflow',
    'Clareza do Overflow'
  ],
  [Area.HBF_C]: [
    'SECTION:DADOS DE OPERAÇÃO',
    'Feed rate (m³/h)',
    'Pressão negativa (Kpa)',
    'SECTION:EQUIPAMENTOS PRINCIPAIS',
    '6C-VF-101',
    '- Sprays',
    '- V-belts',
    '- Pano',
    '- Underpan',
    '- Condições dos resguardos',
    '6C-VF-201',
    '- Sprays',
    '- V-belts',
    '- Pano',
    '- Underpan',
    '- Condições dos resguardos',
    '6C-VF-301',
    '- Sprays',
    '- V-belts',
    '- Pano',
    '- Underpan',
    '- Condições dos resguardos',
    'SECTION:VELOCIDADES DOS BELTS',
    'Velocidade 101 (%)',
    'Velocidade 201 (%)',
    'Velocidade 301 (%)',
    'SECTION:SISTEMAS AUXILIARES',
    'Retorno do tanque 104',
    'VALVULA DE DILUICAO',
    'CORSE SEEDING C1',
    'CORSE SEEDING C2'
  ],
  [Area.HBF_D]: [
    'SECTION:DADOS DE OPERAÇÃO',
    'Feed rate (m³/h)',
    'Pressão negativa (Kpa)',
    'SECTION:EQUIPAMENTOS PRINCIPAIS',
    '6D-VF-101',
    '- Sprays',
    '- V-belts',
    '- Pano',
    '- Underpan',
    '- Condições dos resguardos',
    '6D-VF-201',
    '- Sprays',
    '- V-belts',
    '- Pano',
    '- Underpan',
    '- Condições dos resguardos',
    '6D-VF-301',
    '- Sprays',
    '- V-belts',
    '- Pano',
    '- Underpan',
    '- Condições dos resguardos',
    'SECTION:VELOCIDADES DOS BELTS',
    'Velocidade 101 (%)',
    'Velocidade 201 (%)',
    'Velocidade 301 (%)',
    'SECTION:SISTEMAS AUXILIARES',
    'Retorno do tanque 104',
    'VALVULA DE DILUICAO',
    'CORSE SEEDING D1',
    'CORSE SEEDING D2'
  ]
};
