
import { Area } from './types';

const PUMP_SUB_ITEMS = [
  '- V-belts',
  '- Gaxeta',
  '- temperatura',
  '- vibração',
  '- ruido',
  '- Vazamento'
];

const VACUUM_PUMP_SUB_ITEMS = [
  '- V-belts',
  '- temperatura',
  '- vibração',
  '- ruido',
  '- Vazamento',
  '- Agua de Selagem (m³/h)'
];

export const CHECKLIST_TEMPLATES: Record<Area, string[]> = {
  [Area.DFP2]: [
    'SECTION:LADO C',
    'SECTION:Sieve Bends - LADO C',
    '7C SV 101', '7C SV 201', '7C SV 301', '7C SV 401',
    'SECTION:oversize transfer pp - LADO C',
    '7C PP 117', ...PUMP_SUB_ITEMS,
    'SECTION:flotation feed pps - LADO C',
    '7C PP 118', ...PUMP_SUB_ITEMS,
    '7C PP 119', ...PUMP_SUB_ITEMS,
    'SECTION:flotation circulating pps - LADO C',
    '6C CP 101', ...PUMP_SUB_ITEMS,
    '6C CP 102', ...PUMP_SUB_ITEMS,
    '6C CP 103', ...PUMP_SUB_ITEMS,
    '6C CP 104', ...PUMP_SUB_ITEMS,
    '6C CP 105', ...PUMP_SUB_ITEMS,
    '6C CP 201', ...PUMP_SUB_ITEMS,
    '6C CP 202', ...PUMP_SUB_ITEMS,
    '6C CP 203', ...PUMP_SUB_ITEMS,
    '6C CP 204', ...PUMP_SUB_ITEMS,
    '6C CP 205', ...PUMP_SUB_ITEMS,
    'SECTION:Flotation conc. pp - LADO C',
    '6C PP 108', ...PUMP_SUB_ITEMS,
    'SECTION:Flotation tailing pp - LADO C',
    '7C PP 120', ...PUMP_SUB_ITEMS,
    'SECTION:LADO D',
    'SECTION:Sieve Bends - LADO D',
    '7D SV 101', '7D SV 201', '7D SV 301', '7D SV 401',
    'SECTION:oversize transfer pp - LADO D',
    '7D PP 117', ...PUMP_SUB_ITEMS,
    'SECTION:flotation feed pps - LADO D',
    '7D PP 118', ...PUMP_SUB_ITEMS,
    '7D PP 119', ...PUMP_SUB_ITEMS,
    'SECTION:flotation circulating pps - LADO D',
    '6D CP 101', ...PUMP_SUB_ITEMS,
    '6D CP 102', ...PUMP_SUB_ITEMS,
    '6D CP 103', ...PUMP_SUB_ITEMS,
    '6D CP 104', ...PUMP_SUB_ITEMS,
    '6D CP 105', ...PUMP_SUB_ITEMS,
    '6D CP 201', ...PUMP_SUB_ITEMS,
    '6D CP 202', ...PUMP_SUB_ITEMS,
    '6D CP 203', ...PUMP_SUB_ITEMS,
    '6D CP 204', ...PUMP_SUB_ITEMS,
    '6D CP 205', ...PUMP_SUB_ITEMS,
    'SECTION:Flotation conc. pp - LADO D',
    '6D PP 108', ...PUMP_SUB_ITEMS,
    'SECTION:Flotation tailing pp - LADO D',
    '7D PP 120', ...PUMP_SUB_ITEMS,
    'SECTION:OUTROS SISTEMAS',
    '7C PP 130 (Spillage pp)', ...PUMP_SUB_ITEMS,
    '9C PP 147 (Buster PP)', ...PUMP_SUB_ITEMS
  ],
  [Area.BOMBEAMENTO]: [
    'SECTION:VACUUM PUMPS – PLANTA C',
    '06C-VP-101', ...VACUUM_PUMP_SUB_ITEMS,
    '06C-VP-201', ...VACUUM_PUMP_SUB_ITEMS,
    '06C-VP-301', ...VACUUM_PUMP_SUB_ITEMS,
    '06C-VP-401', ...VACUUM_PUMP_SUB_ITEMS,
    '06C-VP-501', ...VACUUM_PUMP_SUB_ITEMS,
    'SECTION:VACUUM PUMPS – PLANTA D',
    '06D-VP-101', ...VACUUM_PUMP_SUB_ITEMS,
    '06D-VP-201', ...VACUUM_PUMP_SUB_ITEMS,
    '06D-VP-301', ...VACUUM_PUMP_SUB_ITEMS,
    '06D-VP-401', ...VACUUM_PUMP_SUB_ITEMS,
    '06D-VP-501', ...VACUUM_PUMP_SUB_ITEMS,
    'SECTION:FILTRATE PUMPS – PLANTA C',
    '06C-PP-104', ...PUMP_SUB_ITEMS,
    '06C-PP-105', ...PUMP_SUB_ITEMS,
    '06C-PP-204', ...PUMP_SUB_ITEMS,
    '06C-PP-205', ...PUMP_SUB_ITEMS,
    '06C-PP-304', ...PUMP_SUB_ITEMS,
    '06C-PP-305', ...PUMP_SUB_ITEMS,
    'SECTION:FILTRATE PUMPS – PLANTA D',
    '06D-PP-104', ...PUMP_SUB_ITEMS,
    '06D-PP-105', ...PUMP_SUB_ITEMS,
    '06D-PP-204', ...PUMP_SUB_ITEMS,
    '06D-PP-205', ...PUMP_SUB_ITEMS,
    '06D-PP-304', ...PUMP_SUB_ITEMS,
    '06D-PP-305', ...PUMP_SUB_ITEMS,
    'SECTION:BOMBAS DO ESPESSADOR 101 C',
    '7C-PP-101', ...PUMP_SUB_ITEMS,
    '7C-PP-102', ...PUMP_SUB_ITEMS,
    'SECTION:BOMBAS DO ESPESSADOR 101 D',
    '7D-PP-101', ...PUMP_SUB_ITEMS,
    '7D-PP-102', ...PUMP_SUB_ITEMS,
    'SECTION:BOMBAS DO ESPESSADOR 102',
    '7C-PP-107', ...PUMP_SUB_ITEMS,
    '7C-PP-108', ...PUMP_SUB_ITEMS,
    '9C-PP-120', ...PUMP_SUB_ITEMS,
    '9C-PP-128', ...PUMP_SUB_ITEMS,
    'SECTION:BOMBAS DO ESPESSADOR 103',
    '7C-PP-109', ...PUMP_SUB_ITEMS,
    '7C-PP-110', ...PUMP_SUB_ITEMS,
    '9C-PP-112', ...PUMP_SUB_ITEMS,
    '9C-PP-113', ...PUMP_SUB_ITEMS,
    '9C-PP-114', ...PUMP_SUB_ITEMS,
    '9C-PP-121', ...PUMP_SUB_ITEMS,
    '9C-PP-122', ...PUMP_SUB_ITEMS,
    '9C-PP-123', ...PUMP_SUB_ITEMS,
    'SECTION:BOMBAS DOS BUFAS TANK',
    '7C-PP-111', ...PUMP_SUB_ITEMS,
    '7C-PP-112', ...PUMP_SUB_ITEMS,
    '7C-PP-113', ...PUMP_SUB_ITEMS,
    'SECTION:BOMBAS DO SLIMES',
    '7D-PP-107', ...PUMP_SUB_ITEMS,
    '7D-PP-104', ...PUMP_SUB_ITEMS,
    '7D-PP-111', ...PUMP_SUB_ITEMS,
    '7D-PP-108', ...PUMP_SUB_ITEMS,
    'SECTION:BOMBAS DE CLARIFIED C',
    '9C-PP-101', ...PUMP_SUB_ITEMS,
    '9C-PP-102', ...PUMP_SUB_ITEMS,
    '9C-PP-103', ...PUMP_SUB_ITEMS,
    '9C-PP-104', ...PUMP_SUB_ITEMS,
    '9C-PP-105', ...PUMP_SUB_ITEMS,
    '9C-PP-106', ...PUMP_SUB_ITEMS,
    'SECTION:BOMBAS DE CLARIFIED D',
    '9D-PP-101', ...PUMP_SUB_ITEMS,
    '9D-PP-102', ...PUMP_SUB_ITEMS,
    '9D-PP-103', ...PUMP_SUB_ITEMS,
    '9D-PP-104', ...PUMP_SUB_ITEMS,
    '9D-PP-105', ...PUMP_SUB_ITEMS,
    '9D-PP-106', ...PUMP_SUB_ITEMS,
    'SECTION:COLUMN WASH',
    '6C-PP-103', ...PUMP_SUB_ITEMS,
    '6D-PP-103', ...PUMP_SUB_ITEMS,
    'SECTION:FLOTATION FEED',
    '5C-PP-101', ...PUMP_SUB_ITEMS,
    '5D-PP-101', ...PUMP_SUB_ITEMS,
    'SECTION:CLOTH WASH',
    '6C-PP-201', ...PUMP_SUB_ITEMS,
    '6D-PP-201', ...PUMP_SUB_ITEMS,
    'SECTION:CONCENTRADO C',
    '6C-PP-102', ...PUMP_SUB_ITEMS,
    '6C-PP-202', ...PUMP_SUB_ITEMS,
    '6C-PP-302', ...PUMP_SUB_ITEMS,
    'SECTION:CONCENTRADO D',
    '6D-PP-201', ...PUMP_SUB_ITEMS,
    '6D-PP-202', ...PUMP_SUB_ITEMS,
    '6D-PP-203', ...PUMP_SUB_ITEMS,
    'SECTION:SPILLAGE PUMPS',
    '6C-PP-210', ...PUMP_SUB_ITEMS,
    '6C-PP-211', ...PUMP_SUB_ITEMS,
    '6C-PP-212', ...PUMP_SUB_ITEMS,
    '7C-PP-114', ...PUMP_SUB_ITEMS,
    '6C-PP-106', ...PUMP_SUB_ITEMS,
    '6D-PP-210', ...PUMP_SUB_ITEMS,
    '6D-PP-211', ...PUMP_SUB_ITEMS,
    '6D-PP-212', ...PUMP_SUB_ITEMS,
    '7D-PP-109', ...PUMP_SUB_ITEMS,
    '7D-PP-108', ...PUMP_SUB_ITEMS,
    '9D-PP-106', ...PUMP_SUB_ITEMS
  ],
  [Area.ESPESADORES]: [
    'Torque do acionamento (%)',
    'Altura dos braços (Rake)',
    'Fluxo de floculante (m3/h)',
    'Densidade do Underflow',
    'Clareza do Overflow'
  ],
  [Area.HBF_C]: [
    'SECTION:DADOS DE OPERAÇÃO',
    'Feed rate (m³/h)',
    'Pressão negativa (Kpa)',
    'SECTION:EQUIPAMENTOS PRINCIPAIS',
    '6C-VF-101',
    '- Sprays',
    '- V-belts',
    '- Pano',
    '- Underpan',
    '- Condições dos resguardos',
    '6C-VF-201',
    '- Sprays',
    '- V-belts',
    '- Pano',
    '- Underpan',
    '- Condições dos resguardos',
    '6C-VF-301',
    '- Sprays',
    '- V-belts',
    '- Pano',
    '- Underpan',
    '- Condições dos resguardos',
    'SECTION:VELOCIDADES DOS BELTS',
    'Velocidade 101 (%)',
    'Velocidade 201 (%)',
    'Velocidade 301 (%)',
    'SECTION:SISTEMAS AUXILIARES',
    'Retorno do tanque 104',
    'VALVULA DE DILUICAO',
    'CORSE SEEDING C1',
    'CORSE SEEDING C2'
  ],
  [Area.HBF_D]: [
    'SECTION:DADOS DE OPERAÇÃO',
    'Feed rate (m³/h)',
    'Pressão negativa (Kpa)',
    'SECTION:EQUIPAMENTOS PRINCIPAIS',
    '6D-VF-101',
    '- Sprays',
    '- V-belts',
    '- Pano',
    '- Underpan',
    '- Condições dos resguardos',
    '6D-VF-201',
    '- Sprays',
    '- V-belts',
    '- Pano',
    '- Underpan',
    '- Condições dos resguardos',
    '6D-VF-301',
    '- Sprays',
    '- V-belts',
    '- Pano',
    '- Underpan',
    '- Condições dos resguardos',
    'SECTION:VELOCIDADES DOS BELTS',
    'Velocidade 101 (%)',
    'Velocidade 201 (%)',
    'Velocidade 301 (%)',
    'SECTION:SISTEMAS AUXILIARES',
    'Retorno do tanque 104',
    'VALVULA DE DILUICAO',
    'CORSE SEEDING D1',
    'CORSE SEEDING D2'
  ]
};
